# permissions for end users to edit wallets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wallet-editor-role
rules:
- apiGroups:
  - filecoin.io.filecoin.io
  resources:
  - wallets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - filecoin.io.filecoin.io
  resources:
  - wallets/status
  verbs:
  - get
