# permissions for end users to view wallets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wallet-viewer-role
rules:
- apiGroups:
  - filecoin.io.filecoin.io
  resources:
  - wallets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - filecoin.io.filecoin.io
  resources:
  - wallets/status
  verbs:
  - get
